### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by lavrenkov-sketch** [Golodnyi/ntcb#1]
./ntcb start

nohup: redirecting stderr to stdout
Сервер NTCB остановлен
lavrenkovnv@host:~/ntcb-master$

**Comment by Golodnyi** [comment]
Там надо запустить composer install
- .evn.example файл переименовать в .env, заполнить в нем доступ к базе

Еще я писал этот сервер чисто под свои задачи, поэтому он требует наличия юзера server в системе, либо изменить юзера на нужного в ntcb файле.

**Comment by lavrenkov-sketch** [comment]
Есть много трэкеров Navtelecom.  Базу можно пустую?

**Comment by Golodnyi** [comment]
Запушил базу в репозиторий

**Comment by lavrenkov-sketch** [comment]
Для каких моделей вы использовали данный проект?
можно конфиги с трекеров получить?)

**Comment by Golodnyi** [comment]
> Для каких моделей вы использовали данный проект?
> можно конфиги с трекеров получить?)

конфиги дать не смогу, я уже не имею доступа к этому, единственное что помню, в качестве протокола надо выбирать FLEX версии 1.0 или 10, не помню как у них обозначается, включить датчики надо какие вам нужны и все, база рассчитана под все датчики, которые есть во флексе, а вот сам код нет, в export там можно увидеть что инсертится, если надо добавить порты, просто доработать запрос.

Советую скачать flex emulator, через него проверять работу сервера, клиент хорошую отладочную информацию показывает
